# Generated by Django 2.1.3 on 2018-11-19 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacion',
            name='nota',
        ),
    ]
